export const URGENCY = {
  LOW: "Low",
  MEDIUM: "Medium",
  HIGH: "High",
};

export const CATEGORY = {
  PERSONAL: "Personal",
  ACADEMIC: "Academic",
  SOCIAL: "Social",
};

export const NAMES = {
  URGENCY: "URGENCY",
  CATEGORY: "CATEGORY",
  TEXT: "TEXT",
  TIME: "TIME",
};

export const ACTIONS = {
  EDIT: "EDIT",
  DELETE: "DELETE",
  BULKCOMPLETE: "BULKCOMPLETE",
  BULKINCOMPLETE: "BULKINCOMPLETE",
  BULKDELETE: "BULKDELETE",
  RESET: "RESET",
  UPDATE: "UPDATE",
  ADD: "ADD",
  SET_ISCOMPLETED: "SET_ISCOMPLETED",
  TOGGLE_SELECTED_TODO: "TOGGLE_SELECTED_TODO",
  RESET_SELECTED_TODOS: "RESET_SELECTED_TODOS",
};
